server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: petroMS
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.130:3306/petroMS?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: 123


web:
  rsa:
    publicKeyPath: classpath:rsa_public_key.pem
    privateKeyPath: classpath:rsa_private_key.pem

logging:
  config: classpath:log4j2-dev.xml
#  level:
#    org.springframework.boot.autoconfigure: ERROR

petro:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: petroMS
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization

security:
  encrypt:
    key: "lds666"



#  redis:
#    database: ${sky.redis.database}
#    host: ${sky.redis.host}

